package gui;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.StringJoiner;
import java.util.function.Consumer;
import batch.BatchConfiguration;
import batch.BatchErrorException;
import batch.BatchMetrics;
import batch.BatchProcessEvent;
import common.PropertyListener;
import javafx.animation.PauseTransition;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.beans.InvalidationListener;
import javafx.beans.Observable;
import javafx.beans.value.ObservableValue;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.concurrent.WorkerStateEvent;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.Insets;
import javafx.geometry.Side;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ContextMenu;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Dialog;
import javafx.scene.control.Label;
import javafx.scene.control.MenuItem;
import javafx.scene.control.ProgressBar;
import javafx.scene.control.SeparatorMenuItem;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.control.Tooltip;
import javafx.scene.input.Clipboard;
import javafx.scene.input.ClipboardContent;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyCodeCombination;
import javafx.scene.input.KeyCombination;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.MouseButton;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Priority;
import javafx.scene.layout.RowConstraints;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javafx.stage.Window;
import javafx.util.Callback;
import javafx.util.Duration;

/**
 * Provides the JavaFX graphical user interface for configuring and running batch media metadata
 * processing operations.
 *
 * <p>
 * This class manages the main application window, user input controls, batch-processing tasks,
 * progress updates, processing results, and summary dialogs.
 * </p>
 */
public class MediaMetadataGUI extends Application implements EventHandler<ActionEvent>
{
    private Stage stage;
    private BatchTask workerTask;
    private MainViewPane viewPane;
    private ObservableList<FileSummaryRecord> fileRecords;

    /**
     * Initialises the application state before the JavaFX application window is launched.
     */
    @Override
    public void init()
    {
        viewPane = new MainViewPane();
        fileRecords = FXCollections.observableArrayList();
    }

    /**
     * Creates and launches the primary application window.
     *
     * <p>
     * Builds the main layout, configures the scene and stylesheet, attaches action handlers, and
     * configures dynamic user-interface controls.
     * </p>
     *
     * @param primaryStage
     *        the primary stage provided by the JavaFX runtime
     */
    @Override
    public void start(Stage primaryStage)
    {
        RowConstraints fixedRow = new RowConstraints();
        fixedRow.setVgrow(Priority.NEVER);

        RowConstraints fillRow = new RowConstraints();
        fillRow.setVgrow(Priority.ALWAYS);

        GridPane gridPane = new GridPane();
        gridPane.setHgap(10);
        gridPane.setVgap(10);
        gridPane.requestFocus();
        gridPane.setPadding(new Insets(15));
        gridPane.getRowConstraints().addAll(fixedRow, fixedRow, fillRow, fixedRow, fixedRow);

        viewPane.buildLayout(gridPane);

        Scene scene = new Scene(gridPane, 620, 650);
        scene.getStylesheets().add(getClass().getResource("/gui/styles.css").toExternalForm());

        stage = primaryStage;
        stage.setTitle("Image Metadata Structure Viewer");
        stage.setScene(scene);
        stage.show();

        configureDynamicNodes(gridPane);
    }

    @Override
    public void stop()
    {
        TextField sourceText = getById(MainViewPane.SRCID);
        TextField targetText = getById(MainViewPane.TGTID);

        try
        {
            AppSettingsManager.saveSettings(sourceText, targetText);
        }

        catch (IOException exc)
        {
            // TODO: Display GUI error popup
        }
    }

    /**
     * Handles user actions generated by the main application controls. Processes an action event
     * and delegates it to the appropriate application operation.
     */
    @Override
    public void handle(ActionEvent event)
    {
        Object source = event.getSource();

        if (source == viewPane.getSourceBtn())
        {
            ContextMenu menu = (ContextMenu) viewPane.getSourceBtn().getUserData();

            if (menu != null)
            {
                menu.show(viewPane.getSourceBtn(), Side.BOTTOM, 0, 0);
            }
        }

        else if (source == viewPane.getActionBtn())
        {
            executeBatchProcess();
        }

        else if (source == viewPane.getCopyLogBtn())
        {
            copyLogText();
        }

        else if (source == viewPane.getCancelBtn())
        {
            if (workerTask != null)
            {
                workerTask.cancel(true);
            }
        }

        else if (source == viewPane.getViewBtn())
        {
            showSummaryDialog(stage);
        }

        else if (source == viewPane.getClearLogBtn())
        {
            TextArea logArea = (TextArea) viewPane.getClearLogBtn().getUserData();

            if (logArea != null)
            {
                logArea.clear();
            }
        }

        else if (source == viewPane.getExitBtn())
        {
            Platform.exit();
        }
    }

    /**
     * Configures dynamic behaviour and event handlers for the UI controls contained within the
     * specified parent pane.
     *
     * <p>
     * Configures source-field interactions, file chooser operations, clipboard handling, control
     * bindings, dynamic metadata updates, and populates recent location context menus.
     * </p>
     *
     * <b>Important note for developers:</b> When the source text field receives files through
     * paste, their parent directory is stored on the text field via
     * {@link TextField#setUserData(Object)} to provide authoritative base-path context for
     * downstream parsing. If a common parent directory cannot be determined, {@code null} is
     * assigned to indicate that no authoritative base path is available.
     * </p>
     *
     * @param pane
     *        the parent container holding the UI elements to configure
     */
    private void configureDynamicNodes(Parent pane)
    {
        TextField sourceText = MainViewPane.getById(pane, MainViewPane.SRCID);
        TextField targetText = getById(MainViewPane.TGTID);
        TextField prefixText = MainViewPane.getById(pane, MainViewPane.PFXID);
        DatePicker modifyDatePicker = MainViewPane.getById(pane, MainViewPane.DTMID);
        CheckBox showMetadataCheck = MainViewPane.getById(pane, MainViewPane.SHWID);

        try
        {
            AppSettingsManager.loadSettings(sourceText, targetText);
        }

        catch (IOException exc)
        {
            // TODO: Display GUI error popup or log startup warning
        }

        populateRecentHistoryMenu();

        if (sourceText != null)
        {
            sourceText.setOnMouseClicked(new EventHandler<MouseEvent>()
            {
                @Override
                public void handle(MouseEvent event)
                {
                    if (event.getButton() == MouseButton.PRIMARY)
                    {
                        viewPane.getSourceBtn().fire();
                    }
                }
            });

            sourceText.focusedProperty().addListener(new InvalidationListener()
            {
                @Override
                public void invalidated(Observable observable)
                {
                    if (!sourceText.isFocused())
                    {
                        sourceText.setText(sourceText.getText().trim());
                    }
                }
            });

            sourceText.addEventFilter(KeyEvent.KEY_PRESSED, new EventHandler<KeyEvent>()
            {
                @Override
                public void handle(KeyEvent event)
                {
                    KeyCodeCombination shortcut = new KeyCodeCombination(KeyCode.V, KeyCombination.SHORTCUT_DOWN);

                    if (shortcut.match(event))
                    {
                        Clipboard clipboard = Clipboard.getSystemClipboard();

                        if (clipboard.hasString())
                        {
                            String pastedText = clipboard.getString().trim();
                            Path path = Paths.get(pastedText);

                            if (Files.exists(path))
                            {
                                Path parent = path.getParent();

                                sourceText.setText(pastedText);
                                sourceText.setUserData(Files.isDirectory(path) || parent == null ? null : parent.toAbsolutePath().toString());
                                sourceText.setTooltip(new Tooltip(pastedText));
                            }

                            else if (pastedText.contains(","))
                            {
                                Path parentDir = null;
                                String[] parts = pastedText.split("\\s*,\\s*");

                                /* Find the first valid parent directory first */
                                for (String part : parts)
                                {
                                    Path file = Paths.get(part).normalize();

                                    if (file.getParent() != null && Files.isRegularFile(file))
                                    {
                                        parentDir = file.getParent();
                                        break;
                                    }
                                }

                                boolean valid = (parentDir != null);

                                if (valid)
                                {
                                    /* Check that all files are in the same directory. */
                                    for (String part : parts)
                                    {
                                        Path file = Paths.get(part);

                                        if (!file.isAbsolute())
                                        {
                                            file = parentDir.resolve(file);
                                        }

                                        file = file.normalize();

                                        if (!Files.isRegularFile(file) || !parentDir.equals(file.getParent()))
                                        {
                                            valid = false;
                                            break;
                                        }
                                    }
                                }

                                sourceText.setText(pastedText);
                                sourceText.setTooltip(new Tooltip(pastedText));
                                sourceText.setUserData(valid ? parentDir.toAbsolutePath().toString() : null);
                            }

                            else
                            {
                                // TODO: convert to Alert popup
                                System.out.println("Pasted path does not exist [" + pastedText + "]");
                            }
                        }

                        event.consume();
                    }
                }
            });
        }

        if (prefixText != null && showMetadataCheck != null)
        {
            prefixText.disableProperty().bind(showMetadataCheck.selectedProperty());
        }

        if (modifyDatePicker != null && showMetadataCheck != null)
        {
            modifyDatePicker.disableProperty().bind(showMetadataCheck.selectedProperty());
        }

        if (showMetadataCheck != null)
        {
            showMetadataCheck.selectedProperty().addListener(new InvalidationListener()
            {
                @Override
                public void invalidated(Observable observable)
                {
                    viewPane.getActionBtn().setText(showMetadataCheck.isSelected() ? "Display Metadata" : "Run Batch Process");
                }
            });
        }

        viewPane.getSourceBtn().setOnAction(this);
        viewPane.getActionBtn().setOnAction(this);
        viewPane.getExitBtn().setOnAction(this);
        viewPane.getCopyLogBtn().setOnAction(this);
        viewPane.getClearLogBtn().setOnAction(this);
        viewPane.getCancelBtn().setOnAction(this);
        viewPane.getViewBtn().setOnAction(this);
    }

    /**
     * Populates the Source button's context menu with default selection options
     * (Select Folder, Select Specific Files) and recent paths retrieved from persistent storage.
     */
    private void populateRecentHistoryMenu()
    {
        ContextMenu menu = new ContextMenu();
        Button sourceBtn = viewPane.getSourceBtn();
        TextField sourceText = getById(MainViewPane.SRCID);
        List<String> recentPaths = AppSettingsManager.loadRecentSourcePaths();

        if (sourceBtn == null || sourceText == null)
        {
            return;
        }

        MenuItem selectFolder = new MenuItem("Select Folder...");
        selectFolder.setOnAction(new FilePickHandler(sourceText, "Select Source Directory"));

        MenuItem selectFiles = new MenuItem("Select Specific Files...");
        selectFiles.setOnAction(new EventHandler<ActionEvent>()
        {
            @Override
            public void handle(ActionEvent event)
            {
                handleFileSelection();
            }
        });

        menu.getItems().addAll(selectFolder, selectFiles);
        menu.getItems().add(new SeparatorMenuItem());

        if (recentPaths.isEmpty())
        {
            MenuItem emptyItem = new MenuItem("No recent folders");

            emptyItem.setDisable(true);
            menu.getItems().add(emptyItem);
        }

        else
        {
            for (final String pathString : recentPaths)
            {
                MenuItem item = new MenuItem(pathString);

                item.setOnAction(new EventHandler<ActionEvent>()
                {
                    @Override
                    public void handle(ActionEvent event)
                    {
                        sourceText.setText(pathString);
                        sourceText.setTooltip(new Tooltip(pathString));

                        try
                        {
                            Path path = Paths.get(pathString);

                            if (Files.exists(path))
                            {
                                Path parent = Files.isDirectory(path) ? path : path.getParent();
                                sourceText.setUserData(parent != null ? parent.toAbsolutePath().toString() : null);
                            }

                            else
                            {
                                sourceText.setUserData(null);
                            }
                        }

                        catch (InvalidPathException exc)
                        {
                            sourceText.setUserData(null);
                        }
                    }
                });

                menu.getItems().add(item);
            }
        }

        /* Update sourceBtn's user data menu reference */
        sourceBtn.setUserData(menu);
    }

    /**
     * Opens a system {@link FileChooser} dialog allowing users to select multiple input files.
     *
     * <p>
     * When at least one file is selected, the file names are formatted into a comma-separated
     * string and populated into the source text field alongside an updated tooltip.
     * </p>
     */
    private void handleFileSelection()
    {
        TextField sourceText = getById(MainViewPane.SRCID);

        if (sourceText != null)
        {
            FileChooser chooser = new FileChooser();
            String actualText = sourceText.getText().trim();
            File sourceDir = new File(actualText.isEmpty() ? System.getProperty("user.home") : actualText);

            chooser.setTitle("Select Source Files");

            if (sourceDir.isDirectory())
            {
                chooser.setInitialDirectory(sourceDir);
            }

            List<File> files = chooser.showOpenMultipleDialog(stage);

            if (files != null && !files.isEmpty())
            {
                StringJoiner joiner = new StringJoiner(", ");

                for (File file : files)
                {
                    joiner.add(file.getName());
                }

                String joined = joiner.toString();

                sourceText.setText(joined);
                sourceText.setTooltip(new Tooltip(joined));
                sourceText.setUserData(files.get(0).getParentFile().getAbsolutePath());
            }
        }
    }

    /**
     * Creates, configures, and starts a background batch-processing task.
     *
     * <p>
     * Resets the current processing results, builds the batch configuration from the user-interface
     * settings, establishes listeners for processing progress and results, and starts the task on
     * a background thread.
     * </p>
     *
     * <p>
     * Updates to JavaFX user-interface controls are performed on the JavaFX application thread.
     * </p>
     */
    private void executeBatchProcess()
    {
        BatchConfiguration config;
        Button actionBtn = viewPane.getActionBtn();
        Button cancelBtn = viewPane.getCancelBtn();
        Button copyLogBtn = viewPane.getCopyLogBtn();
        Button clearLogBtn = viewPane.getClearLogBtn();
        ProgressBar progressBar = viewPane.getProgressBar();
        TextArea logArea = (TextArea) clearLogBtn.getUserData();
        Label progressLabel = (Label) progressBar.getUserData();
        CheckBox showMetadata = getById(MainViewPane.SHWID);
        boolean metaDisplay = (showMetadata != null && showMetadata.isSelected());

        if (logArea != null)
        {
            logArea.clear();
            fileRecords.clear();
            StatRecord.resetAll();

            try
            {
                Parent root = stage.getScene().getRoot();
                config = new ConfigurationBuilder(root).build();
            }

            catch (BatchErrorException exc)
            {
                progressLabel.setText("Configuration error");
                GUIUtils.launchPopup("Invalid File Selection", exc.getMessage(), AlertType.ERROR);
                return;
            }

            workerTask = new BatchTask(config, logArea, progressBar, metaDisplay);

            workerTask.setFileSummaryListener(new PropertyListener()
            {
                @Override
                public void accept(String key, Object value)
                {
                    // Received from BatchTask
                    if (value instanceof BatchProcessEvent)
                    {
                        BatchProcessEvent event = (BatchProcessEvent) value;

                        long size = event.getTargetSize();
                        String source = event.getSourceName();
                        String target = event.getTargetName();
                        String status = event.isSuccess() ? "Completed" : "Failed";

                        Platform.runLater(new Runnable()
                        {
                            @Override
                            public void run()
                            {
                                fileRecords.add(new FileSummaryRecord(source, target, status, size));
                            }
                        });
                    }
                }
            });

            workerTask.setOnFileScanned(new Consumer<Integer>()
            {
                @Override
                public void accept(Integer count)
                {
                    Platform.runLater(new Runnable()
                    {
                        @Override
                        public void run()
                        {
                            StatRecord.SOURCE_FILES.setValue(count);
                        }
                    });
                }
            });

            workerTask.setOnFileProcessed(new Consumer<Integer>()
            {
                @Override
                public void accept(Integer count)
                {
                    Platform.runLater(new Runnable()
                    {
                        @Override
                        public void run()
                        {
                            StatRecord.TARGET_FILES.setValue(count);
                        }
                    });
                }
            });

            workerTask.setOnSucceeded(new EventHandler<WorkerStateEvent>()
            {
                @Override
                public void handle(WorkerStateEvent event)
                {
                    BatchMetrics stats = workerTask.getValue();

                    if (stats != null)
                    {
                        StatRecord.SOURCE_FILES.setValue(stats.getScanned());
                        StatRecord.TARGET_FILES.setValue(stats.getProcessed());
                        StatRecord.FILES_SKIPPED.setValue(stats.getFilesSkippedCount());
                        StatRecord.TOTAL_SIZE.setValue(String.format("%.2f MB", stats.getTotalTargetSizeMB()));
                    }

                    resetControlStates(progressLabel);

                    Platform.runLater(new Runnable()
                    {
                        @Override
                        public void run()
                        {
                            GUIUtils.launchPopup("Process Complete", "Batch processing completed", AlertType.INFORMATION);
                        }
                    });
                }
            });

            workerTask.setOnFailed(new EventHandler<WorkerStateEvent>()
            {
                @Override
                public void handle(WorkerStateEvent event)
                {
                    Throwable exc = workerTask.getException();
                    String msg = (exc != null && exc.getMessage() != null ? exc.getMessage() : "An unknown error occurred.");

                    resetControlStates(progressLabel);
                    GUIUtils.launchPopup("Processing Error", msg, AlertType.ERROR);
                }
            });

            workerTask.setOnCancelled(new EventHandler<WorkerStateEvent>()
            {
                @Override
                public void handle(WorkerStateEvent event)
                {
                    resetControlStates(progressLabel);
                }
            });

            actionBtn.setDisable(true);
            cancelBtn.setDisable(false);
            copyLogBtn.setDisable(true);
            progressLabel.textProperty().bind(workerTask.messageProperty());

            Thread worker = new Thread(workerTask);
            worker.setDaemon(true);
            worker.start();
        }
    }

    /**
     * Copies the content of the log text area to the system clipboard and briefly highlights the
     * text to provide visual feedback to the user.
     *
     * <p>
     * If the log area contains text, its entire contents are transferred to the system clipboard. A
     * temporary visual flash effect is applied using a {@link PauseTransition} before restoring the
     * original control styling and clearing the selection.
     * </p>
     */
    private void copyLogText()
    {
        TextArea logArea = (TextArea) viewPane.getClearLogBtn().getUserData();

        if (logArea != null && !logArea.getText().isEmpty())
        {
            ClipboardContent content = new ClipboardContent();
            content.putString(logArea.getText());
            Clipboard.getSystemClipboard().setContent(content);

            String originalStyle = logArea.getStyle();
            logArea.setStyle(originalStyle + " -fx-highlight-fill: #a8e6cf; -fx-highlight-text-fill: #000000;");

            logArea.selectAll();

            PauseTransition flash = new PauseTransition(Duration.millis(550));

            flash.setOnFinished(new EventHandler<ActionEvent>()
            {
                @Override
                public void handle(ActionEvent event)
                {
                    logArea.deselect();
                    logArea.setStyle(originalStyle);
                }
            });

            flash.play();
        }
    }

    /**
     * Resets action buttons, progress bars, and status labels after a task finishes, fails, or
     * cancels.
     *
     * @param progressLabel
     *        the UI label displaying task progress text
     */
    private void resetControlStates(Label progressLabel)
    {
        Button actionBtn = viewPane.getActionBtn();
        Button cancelBtn = viewPane.getCancelBtn();
        Button copyLogBtn = viewPane.getCopyLogBtn();
        ProgressBar progressBar = viewPane.getProgressBar();

        actionBtn.setDisable(false);
        actionBtn.getScene().getRoot().requestFocus();
        cancelBtn.setDisable(true);
        copyLogBtn.setDisable(false);
        workerTask = null;

        PauseTransition delay = new PauseTransition(Duration.seconds(3));

        delay.setOnFinished(new EventHandler<ActionEvent>()
        {
            @Override
            public void handle(ActionEvent event)
            {
                progressLabel.textProperty().unbind();
                progressBar.progressProperty().unbind();
                progressLabel.setText("");
                progressBar.setProgress(0.0);
            }
        });

        delay.play();
    }

    /**
     * Opens a summary dialog containing details and processing statuses for all processed files.
     *
     * @param ownerWindow
     *        the owning window stage for this modal dialog
     */
    private void showSummaryDialog(Window ownerWindow)
    {
        Dialog<Void> dialog = new Dialog<>();
        dialog.setTitle("Batch Processing Summary");
        dialog.setHeaderText("Detailed Processing Results");
        dialog.initOwner(ownerWindow);

        dialog.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);

        TableView<FileSummaryRecord> table = new TableView<>();
        table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);

        TableColumn<FileSummaryRecord, String> sourceCol = new TableColumn<>("Source File");

        sourceCol.setCellValueFactory(new Callback<TableColumn.CellDataFeatures<FileSummaryRecord, String>, ObservableValue<String>>()
        {
            @Override
            public ObservableValue<String> call(TableColumn.CellDataFeatures<FileSummaryRecord, String> cellData)
            {
                return cellData.getValue().sourceNameProperty();
            }
        });

        sourceCol.setPrefWidth(200);

        TableColumn<FileSummaryRecord, String> targetCol = new TableColumn<>("Target File");

        targetCol.setCellValueFactory(new Callback<TableColumn.CellDataFeatures<FileSummaryRecord, String>, ObservableValue<String>>()
        {
            @Override
            public ObservableValue<String> call(TableColumn.CellDataFeatures<FileSummaryRecord, String> cellData)
            {
                return cellData.getValue().targetNameProperty();
            }
        });

        targetCol.setPrefWidth(200);

        TableColumn<FileSummaryRecord, String> statusCol = new TableColumn<>("Status");

        statusCol.setCellValueFactory(new Callback<TableColumn.CellDataFeatures<FileSummaryRecord, String>, ObservableValue<String>>()
        {
            @Override
            public ObservableValue<String> call(TableColumn.CellDataFeatures<FileSummaryRecord, String> cellData)
            {
                return cellData.getValue().statusProperty();
            }
        });

        statusCol.setPrefWidth(120);

        table.getColumns().add(sourceCol);
        table.getColumns().add(targetCol);
        table.getColumns().add(statusCol);
        table.setItems(fileRecords);

        dialog.getDialogPane().setContent(table);
        dialog.getDialogPane().setPrefSize(550, 320);
        dialog.showAndWait();
    }

    /**
     * Convenience method to retrieve a JavaFX node by its ID from the root scene node.
     *
     * @param <T>
     *        the expected node type
     * @param id
     *        the JavaFX ID of the target node
     * @return the matching node cast to type {@code T}, or {@code null} if not found
     */
    private <T extends Node> T getById(String id)
    {
        if (stage != null && stage.getScene() != null)
        {
            return GUIUtils.getById(stage.getScene().getRoot(), id);
        }

        return null;
    }

    /**
     * Launches the JavaFX application.
     *
     * @param args
     *        command-line arguments supplied to the application
     */
    public static void main(String[] args)
    {
        launch(args);
    }
}